name: Run pytest

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pavelzw/pytest-action@v2
        with:
            verbose: true
            emoji: false
            job-summary: true
            custom-arguments: '-q'
            click-to-expand: true
            report-title: 'Test Report'